-- 1. TẠO DATABASE
DROP DATABASE IF EXISTS PTTKHT;
CREATE DATABASE PTTKHT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE PTTKHT;

-- =======================================================
-- 2. TẠO BẢNG (THEO THỨ TỰ RÀNG BUỘC)
-- =======================================================

-- 2.1. LOAI_HANG
CREATE TABLE LOAI_HANG (
    MaLoai INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenLoai NVARCHAR(100) NOT NULL,
    MoTa TEXT,
    NhomCha NVARCHAR(100),
    Tags NVARCHAR(255),
    TrangThai TINYINT UNSIGNED DEFAULT 1,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.2. TAI_KHOAN
CREATE TABLE TAI_KHOAN (
    MaNV INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL,
    HoTen NVARCHAR(100) NOT NULL,
    Email VARCHAR(100),
    QuyenHan TINYINT UNSIGNED DEFAULT 1,
    TrangThai TINYINT UNSIGNED DEFAULT 1,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.3. NHA_CUNG_CAP
CREATE TABLE NHA_CUNG_CAP (
    MaNCC INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenNCC NVARCHAR(200) NOT NULL,
    DiaChi NVARCHAR(255),
    SoDienThoai VARCHAR(20),
    Email VARCHAR(100),
    NguoiLienHe NVARCHAR(100),
    SoTienNo DECIMAL(15,0) UNSIGNED DEFAULT 0,
    HanThanhToan DATE,
    GhiChu TEXT,
    TrangThai TINYINT UNSIGNED DEFAULT 1,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.4. HANG_HOA (Quan trọng: Khớp kiểu dữ liệu MaLoai, MaNCC)
CREATE TABLE HANG_HOA (
    MaHang VARCHAR(50) PRIMARY KEY,
    TenHang NVARCHAR(200) NOT NULL,
    MoTa TEXT,
    MaLoai INT UNSIGNED NOT NULL,
    MaNCC INT UNSIGNED,
    Size VARCHAR(10),
    MauSac NVARCHAR(20),
    DonViTinh NVARCHAR(20) DEFAULT 'Cái',
    SoLuongTon INT UNSIGNED DEFAULT 0,
    DonGiaNhap DECIMAL(15,0) UNSIGNED NOT NULL,
    DonGiaBan DECIMAL(15,0) UNSIGNED NOT NULL,
    GiaKhuyenMai DECIMAL(15,0) UNSIGNED DEFAULT 0,
    AnhMinhHoa VARCHAR(255),
    TrangThai TINYINT UNSIGNED DEFAULT 1,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (MaLoai) REFERENCES LOAI_HANG(MaLoai) ON UPDATE CASCADE,
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.5. HOA_DON
CREATE TABLE HOA_DON (
    MaHD VARCHAR(20) PRIMARY KEY,
    NgayLap DATETIME DEFAULT CURRENT_TIMESTAMP,
    LoaiHD TINYINT UNSIGNED NOT NULL COMMENT '0: Nhập, 1: Xuất',
    MaNV INT UNSIGNED NOT NULL,
    TongTien DECIMAL(15,0) UNSIGNED DEFAULT 0,
    GhiChu TEXT,
    TrangThai TINYINT UNSIGNED DEFAULT 1,
    FOREIGN KEY (MaNV) REFERENCES TAI_KHOAN(MaNV) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.6. CHI_TIET_HOA_DON
CREATE TABLE CHI_TIET_HOA_DON (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaHD VARCHAR(20) NOT NULL,
    MaHang VARCHAR(50) NOT NULL,
    SoLuong INT UNSIGNED NOT NULL,
    DonGia DECIMAL(15,0) UNSIGNED NOT NULL,
    ThanhTien DECIMAL(15,0) UNSIGNED NOT NULL,
    
    FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHang) REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.7. PHIEU_NHAP_KHO
CREATE TABLE PHIEU_NHAP_KHO (
    MaPNK VARCHAR(20) PRIMARY KEY,
    NgayNhap DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaNCC INT UNSIGNED,
    MaNV INT UNSIGNED NOT NULL,
    TongTien DECIMAL(15,0) UNSIGNED DEFAULT 0,
    ChietKhau DECIMAL(15,0) UNSIGNED DEFAULT 0,
    TrangThai TINYINT UNSIGNED DEFAULT 0,
    GhiChu TEXT,
    
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC) ON DELETE SET NULL ON UPDATE CASCADE,
    FOREIGN KEY (MaNV) REFERENCES TAI_KHOAN(MaNV) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.8. CHI_TIET_PHIEU_NHAP_KHO
CREATE TABLE CHI_TIET_PHIEU_NHAP_KHO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaPNK VARCHAR(20) NOT NULL,
    MaHang VARCHAR(50) NOT NULL,
    SoLuong INT UNSIGNED NOT NULL,
    DonGiaNhap DECIMAL(15,0) UNSIGNED NOT NULL,
    ThanhTien DECIMAL(15,0) UNSIGNED NOT NULL,
    
    FOREIGN KEY (MaPNK) REFERENCES PHIEU_NHAP_KHO(MaPNK) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHang) REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.9. PHIEU_XUAT_KHO (Sửa MaNV thành INT UNSIGNED)
CREATE TABLE PHIEU_XUAT_KHO (
    MaPXK VARCHAR(20) PRIMARY KEY,
    NgayXuat DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaNV INT UNSIGNED NOT NULL, 
    NguoiNhan NVARCHAR(100),
    ChietKhau DECIMAL(15, 0) UNSIGNED DEFAULT 0,
    TrangThai TINYINT UNSIGNED DEFAULT 1,
    GhiChu TEXT,
    
    FOREIGN KEY (MaNV) REFERENCES TAI_KHOAN(MaNV) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.10. CHI_TIET_PHIEU_XUAT_KHO (Sửa MaHang thành VARCHAR 50)
CREATE TABLE CHI_TIET_PHIEU_XUAT_KHO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaPXK VARCHAR(20) NOT NULL,
    MaHang VARCHAR(50) NOT NULL, 
    SoLuong INT UNSIGNED NOT NULL,
    DonGiaXuat DECIMAL(15,0) UNSIGNED NOT NULL,
    ThanhTien DECIMAL(15,0) UNSIGNED NOT NULL,
    
    FOREIGN KEY (MaPXK) REFERENCES PHIEU_XUAT_KHO(MaPXK) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHang) REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.11. PHIEU_KIEM_KE
CREATE TABLE PHIEU_KIEM_KE (
    MaPKK VARCHAR(20) PRIMARY KEY,
    NgayKiemKe DATE NOT NULL,
    MaNV INT UNSIGNED NOT NULL,
    TrangThai TINYINT UNSIGNED DEFAULT 0,
    GhiChu TEXT,
    FOREIGN KEY (MaNV) REFERENCES TAI_KHOAN(MaNV) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.12. CHI_TIET_PHIEU_KIEM_KE (Thêm ID và LyDoChenhLech)
CREATE TABLE CHI_TIET_PHIEU_KIEM_KE (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaPKK VARCHAR(20) NOT NULL,
    MaHang VARCHAR(50) NOT NULL,
    SoLuongTonKho INT UNSIGNED NOT NULL,
    SoLuongThucTe INT UNSIGNED NOT NULL,
    ChenhLech INT NOT NULL,
    LyDoChenhLech NVARCHAR(255),
    
    FOREIGN KEY (MaPKK) REFERENCES PHIEU_KIEM_KE(MaPKK) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHang) REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.13. BANG_GIA (Thêm MoTa, LoaiTienTe)
CREATE TABLE BANG_GIA (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenBangGia NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255),
    LoaiTienTe VARCHAR(10) DEFAULT 'VNĐ',
    TrangThai TINYINT DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- 2.14. CHUONG_TRINH_KM (Thêm PhamVi, MucGiam)
CREATE TABLE CHUONG_TRINH_KM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenCT NVARCHAR(200) NOT NULL,
    MaCode VARCHAR(50),
    NgayBatDau DATE,
    NgayKetThuc DATE,
    PhamViApDung NVARCHAR(255),
    MucGiam NVARCHAR(100),
    TrangThai TINYINT DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;