-- 1. TẠO DATABASE
DROP DATABASE IF EXISTS PTTKHT;
CREATE DATABASE PTTKHT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE PTTKHT;

-- ============================================
-- 2. DANH MỤC & NGƯỜI DÙNG
-- ============================================

-- 2.1. Bảng LOAI_HANG (Category)
CREATE TABLE LOAI_HANG (
    MaLoai INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenLoai NVARCHAR(100) NOT NULL,
    MoTa TEXT NULL,
    NhomCha NVARCHAR(100) NULL,
    Tags NVARCHAR(255) NULL,
    TrangThai TINYINT UNSIGNED DEFAULT 1 COMMENT '1: Hoạt động, 0: Vô hiệu',
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_TenLoai (TenLoai),
    INDEX idx_TrangThai (TrangThai)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2.2. Bảng TAI_KHOAN (User) 
CREATE TABLE TAI_KHOAN (
    MaNV INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenDangNhap VARCHAR(50) NOT NULL UNIQUE,
    MatKhau VARCHAR(255) NOT NULL COMMENT 'Lưu Hash (MD5/SHA256)',
    HoTen NVARCHAR(100) NOT NULL,
    Email VARCHAR(100) NULL,
    QuyenHan TINYINT UNSIGNED DEFAULT 1 COMMENT '0: Admin, 1: NhanVien',
    TrangThai TINYINT UNSIGNED DEFAULT 1 COMMENT '1: Hoạt động, 0: Khóa',
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_TenDangNhap (TenDangNhap),
    INDEX idx_QuyenHan (QuyenHan)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2.3. Bảng NHA_CUNG_CAP (Supplier) 
CREATE TABLE NHA_CUNG_CAP (
    MaNCC INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenNCC NVARCHAR(200) NOT NULL,
    DiaChi NVARCHAR(255) NULL,
    SoDienThoai VARCHAR(20) NULL,
    Email VARCHAR(100) NULL,
    NguoiLienHe NVARCHAR(100) NULL,
    SoTienNo DECIMAL(15, 0) UNSIGNED DEFAULT 0 CHECK (SoTienNo >= 0),
    HanThanhToan DATE NULL,
    TrangThai TINYINT UNSIGNED DEFAULT 1 COMMENT '1: Hoạt động, 0: Ngừng hợp tác',
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_TenNCC (TenNCC),
    INDEX idx_SoDienThoai (SoDienThoai)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 3. SẢN PHẨM & GIÁ 
-- ============================================

-- 3.1. Bảng HANG_HOA (Product) - [MERGED]
CREATE TABLE HANG_HOA (
    MaHang VARCHAR(50) PRIMARY KEY,
    TenHang NVARCHAR(200) NOT NULL,
    MaLoai INT UNSIGNED NOT NULL,
    MaNCC INT UNSIGNED NULL COMMENT 'Nhà cung cấp chính/mặc định',
    Size VARCHAR(10) NULL,
    MauSac NVARCHAR(20) NULL,
    DonViTinh NVARCHAR(20) DEFAULT 'Cái',
    SoLuongTon INT UNSIGNED DEFAULT 0 CHECK (SoLuongTon >= 0),
    DonGiaNhap DECIMAL(15, 0) UNSIGNED NOT NULL CHECK (DonGiaNhap >= 0),
    DonGiaBan DECIMAL(15, 0) UNSIGNED NOT NULL CHECK (DonGiaBan >= 0),
    GiaKhuyenMai DECIMAL(15, 0) UNSIGNED DEFAULT 0 CHECK (GiaKhuyenMai >= 0) COMMENT 'Giá sau khi giảm (nếu có)',
    AnhMinhHoa VARCHAR(255) NULL,
    TrangThai TINYINT UNSIGNED DEFAULT 1 COMMENT '1: Đang bán, 0: Ngừng bán',
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    FOREIGN KEY (MaLoai) REFERENCES LOAI_HANG(MaLoai) ON UPDATE CASCADE ON DELETE RESTRICT,
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC) ON UPDATE CASCADE ON DELETE SET NULL,
    
    INDEX idx_TenHang (TenHang),
    INDEX idx_MaLoai (MaLoai),
    INDEX idx_TrangThai (TrangThai),
    INDEX idx_SoLuongTon (SoLuongTon)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3.2. Bảng BANG_GIA (Price List) 
CREATE TABLE BANG_GIA (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TenBangGia NVARCHAR(100) NOT NULL,
    MoTa NVARCHAR(255) NULL,
    LoaiTienTe VARCHAR(10) DEFAULT 'VNĐ',
    TrangThai TINYINT UNSIGNED DEFAULT 1,
    NgayTao DATETIME DEFAULT CURRENT_TIMESTAMP,
    NgayCapNhat DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3.3. Bảng CHUONG_TRINH_KM (Promotion) 
CREATE TABLE CHUONG_TRINH_KM (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    TenCT NVARCHAR(200) NOT NULL,
    MaCode VARCHAR(50),
    NgayBatDau DATE,
    NgayKetThuc DATE,
    PhamViApDung NVARCHAR(255),
    MucGiam NVARCHAR(100),
    TrangThai TINYINT DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
-- ============================================
-- 4. GIAO DỊCH (HÓA ĐƠN)
-- ============================================

-- 4.1. Bảng HOA_DON (Invoice Header) 
CREATE TABLE HOA_DON (
    MaHD VARCHAR(20) PRIMARY KEY,
    NgayLap DATETIME DEFAULT CURRENT_TIMESTAMP,
    LoaiHD TINYINT UNSIGNED NOT NULL COMMENT '0: Phieu Nhap, 1: Phieu Xuat',
    MaNV INT UNSIGNED NOT NULL,
    TongTien DECIMAL(15, 0) UNSIGNED DEFAULT 0 CHECK (TongTien >= 0),
    GhiChu TEXT NULL,
    TrangThai TINYINT UNSIGNED DEFAULT 1 COMMENT '1: Hợp lệ, 0: Đã hủy',
    FOREIGN KEY (MaNV) REFERENCES TAI_KHOAN(MaNV) ON UPDATE CASCADE ON DELETE RESTRICT,
    INDEX idx_NgayLap (NgayLap),
    INDEX idx_LoaiHD (LoaiHD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 4.2. Bảng CHI_TIET_HOA_DON (Invoice Detail) 
CREATE TABLE CHI_TIET_HOA_DON (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaHD VARCHAR(20) NOT NULL,
    MaHang VARCHAR(50) NOT NULL,
    SoLuong INT UNSIGNED NOT NULL CHECK (SoLuong > 0),
    DonGia DECIMAL(15, 0) UNSIGNED NOT NULL CHECK (DonGia >= 0),
    ThanhTien DECIMAL(15, 0) UNSIGNED NOT NULL CHECK (ThanhTien >= 0),
    FOREIGN KEY (MaHD) REFERENCES HOA_DON(MaHD) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHang) REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE KEY uk_MaHD_MaHang (MaHD, MaHang) COMMENT 'Mỗi hóa đơn chỉ có 1 dòng cho 1 mặt hàng'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================
-- 5. QUẢN LÝ KHO (NHẬP - XUẤT - KIỂM KÊ)
-- ============================================

-- 5.1. Bảng PHIEU_NHAP_KHO 
CREATE TABLE PHIEU_NHAP_KHO (
    MaPNK VARCHAR(20) PRIMARY KEY,
    NgayNhap DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaNCC INT UNSIGNED NULL,
    MaNV INT UNSIGNED NOT NULL,
    TongTien DECIMAL(15, 0) UNSIGNED DEFAULT 0 CHECK (TongTien >= 0),
    ChietKhau DECIMAL(15, 0) UNSIGNED DEFAULT 0 CHECK (ChietKhau >= 0),
    TrangThai TINYINT UNSIGNED DEFAULT 0 COMMENT '0: Đang xử lý, 1: Hoàn thành',
    GhiChu TEXT NULL,
    FOREIGN KEY (MaNCC) REFERENCES NHA_CUNG_CAP(MaNCC) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (MaNV) REFERENCES TAI_KHOAN(MaNV) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5.2. CHI_TIET_PHIEU_NHAP_KHO 
CREATE TABLE CHI_TIET_PHIEU_NHAP_KHO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaPNK VARCHAR(20) NOT NULL,
    MaHang VARCHAR(50) NOT NULL,
    SoLuong INT UNSIGNED NOT NULL CHECK (SoLuong > 0),
    DonGiaNhap DECIMAL(15, 0) UNSIGNED NOT NULL CHECK (DonGiaNhap >= 0),
    ThanhTien DECIMAL(15, 0) UNSIGNED NOT NULL CHECK (ThanhTien >= 0),
    FOREIGN KEY (MaPNK) REFERENCES PHIEU_NHAP_KHO(MaPNK) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHang) REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE KEY uk_MaPNK_MaHang (MaPNK, MaHang)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5.3. Bảng PHIEU_XUAT_KHO 
CREATE TABLE PHIEU_XUAT_KHO (
    MaPXK VARCHAR(20) PRIMARY KEY,
    NgayXuat DATETIME DEFAULT CURRENT_TIMESTAMP,
    MaNV INT UNSIGNED NOT NULL,
    NguoiNhan NVARCHAR(255) NULL,
    ChietKhau DECIMAL(15, 0) UNSIGNED DEFAULT 0 CHECK (ChietKhau >= 0),
    TrangThai TINYINT UNSIGNED DEFAULT 0 COMMENT '0: Đang xử lý, 1: Hoàn thành',
    GhiChu TEXT NULL,
    FOREIGN KEY (MaNV) REFERENCES TAI_KHOAN(MaNV) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5.4. CHI_TIET_PHIEU_XUAT_KHO
CREATE TABLE CHI_TIET_PHIEU_XUAT_KHO (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaPXK VARCHAR(20) NOT NULL,
    MaHang VARCHAR(50) NOT NULL,
    SoLuong INT UNSIGNED NOT NULL CHECK (SoLuong > 0),
    DonGiaXuat DECIMAL(15, 0) UNSIGNED NOT NULL CHECK (DonGiaXuat >= 0),
    ThanhTien DECIMAL(15, 0) UNSIGNED NOT NULL CHECK (ThanhTien >= 0),
    FOREIGN KEY (MaPXK) REFERENCES PHIEU_XUAT_KHO(MaPXK) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHang) REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE KEY uk_MaPXK_MaHang (MaPXK, MaHang)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5.5. Bảng PHIEU_KIEM_KE 
CREATE TABLE PHIEU_KIEM_KE (
    MaPKK VARCHAR(20) PRIMARY KEY,
    NgayKiemKe DATE NOT NULL,
    MaNV INT UNSIGNED NOT NULL,
    TrangThai TINYINT UNSIGNED DEFAULT 0 COMMENT '0: Đang kiểm, 1: Đã hoàn thành, 2: Đã hủy',
    GhiChu TEXT NULL,
    FOREIGN KEY (MaNV) REFERENCES TAI_KHOAN(MaNV) ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 5.6. CHI_TIET_PHIEU_KIEM_KE 
CREATE TABLE CHI_TIET_PHIEU_KIEM_KE (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    MaPKK VARCHAR(20) NOT NULL,
    MaHang VARCHAR(50) NOT NULL,
    SoLuongTonKho INT UNSIGNED NOT NULL,
    SoLuongThucTe INT UNSIGNED NOT NULL,
    ChenhLech INT NOT NULL COMMENT 'ThucTe - TonKho (Có thể âm)',
    LyDoChenhLech NVARCHAR(255) NULL,
    FOREIGN KEY (MaPKK) REFERENCES PHIEU_KIEM_KE(MaPKK) ON DELETE CASCADE ON UPDATE CASCADE,
    FOREIGN KEY (MaHang) REFERENCES HANG_HOA(MaHang) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE KEY uk_MaPKK_MaHang (MaPKK, MaHang)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;